credentials:
  usernames:
    hasyim:
      name: Hasyim
      password: $2b$12$I83EFJJcA3Gq.M2kaOMmAO/RJZ3QJeE5u/8nfFNVkcF/viB3XDHqq
    kakde:
      name: Kak Gede
      password: $2b$12$JQxN.V60DrXhmTWQ2XvuIeIO.tORQw3xCE/Ywi92qzNcaUgE99b1e
cookie:
  expiry_days: 30
  name: coach_login
  key: asdfghjkl